apps/authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from apps.authentication import views

app_name = "apps.authentication"


urlpatterns = [
    path("login/", views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),

    path('settings/', views.UserSettingsView.as_view(), name='settings'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),

    path('users/', views.UsersProfilesView.as_view(), name='users-profiles'),
    path('users/<int:pk>/position/', views.PositionAddView.as_view(), name='update-role'),

    path('activate/<uidb64>/<token>', views.ActivateView.as_view(), name='activate'),

    path("reset_password/", views.PasswordResetView.as_view(), name='reset-password'),

    path(r"reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

]

apps/home/urls.py
from django.urls import path

from apps.home import views

app_name = "apps.home"


urlpatterns = [
    path("", views.HomeView.as_view(), name='home-page')
]

apps/management/urls.py
from django.urls import path

from apps.management import views

app_name = "apps.management"


urlpatterns = [
    # list views
    path("", views.CourseListView.as_view(), name='all-courses'),
    path("my/", views.MyCourseListView.as_view(), name='my-courses'),
    # detail views
    path("<int:pk>/", views.CourseDetailView.as_view(), name='course-detail'),
    # create views
    path("add/", views.CourseCreateView.as_view(), name='create_course'),
    path("<int:pk>/tasks/add/", views.TaskCreateView.as_view(), name='create-task'),
    path("<int:pk>/lectures/add/", views.LectureCreateView.as_view(), name='create-lecture'),
    # update views
    path("<int:pk>/students/update", views.UpdateCourseView.as_view(), name='update-course'),
    # template views
    path("<int:pk>/ratings/", views.RatingView.as_view(), name='ratings'),

]

urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.authentication import JWTAuthentication

from config.settings import base


schema_view = get_schema_view(
    openapi.Info(
        title="LMS API",
        default_version='v1',
        description="",
        contact=openapi.Contact(email="contact@lms.com"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny,],
    authentication_classes=[JWTAuthentication]
)


api_urls = [
    path('courses/', include("apps.management.api_urls")),
    path('courses/<int:pk>/tasks/<int:pktask>/', include("apps.assessment.api_urls")),

    path('accounts/', include("apps.authentication.api_urls")),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('courses/', include('apps.management.urls', namespace='management')),
    path('accounts/', include('apps.authentication.urls', namespace='authentication')),
    path('tinymce/', include('tinymce.urls')),
    path('courses/<int:pk>/tasks/<int:pktask>/', include('apps.assessment.urls', namespace='assessment')),
    path('', include('social_django.urls', namespace='social')),

    path('api/', include(api_urls)),



] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT) \
    + static(base.STATIC_URL, document_root=base.STATIC_ROOT)


if base.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += debug_toolbar_urls()




# todo https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/Django/Sessions
# todo try to do data migrations (DML) while dividing app for a few new apps
# todo https://www.geeksforgeeks.org/software-engineering-coupling-and-cohesion/ ; two scoops of django
# todo check pbkdf2 storage password standard; c
# todo книжка искусство джанго
# todo check oauth2, jwt
# todo dive deeper into celery, celery beat, celery beat for task with course data, celery results, caching with redis
# todo check AJAX, GraphQL, jQuery
# todo high scalability .com site to research microservices examples
# todo react js/flux for stupid people

# todo check vim book
# todo implement vue js and nginx

#todo change  .env to secret manager in aws usage for cloud server

apps/home/views.py
from django.views.generic import TemplateView


# # Create your views here.
class HomeView(TemplateView):
    template_name = 'index.html'

apps/home/templates/home.html
{#{% load static %}#}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans title %}</title>
    {%  block style %} {% endblock %}
</head>
<body>
<h1>{% trans "Welcome to our school!" %}</h1>
{#     <img class="welcome-picture" src="{% static 'Stay.jpg' %}" alt="There had to be a picture">#}
</body>
<br>
<a href="{% url "management:all-courses" %}">{% trans "Courses available" %}</a>

{% if user.is_authenticated %}
    <p>{% trans "Hello" %}, {{ user.username }}!</p> <br>
    <a href="{% url 'management:my-courses' %}">{% trans "My Courses" %}</a>
    <hr>
    <a href="{% url 'authentication:profile' %}">{% trans "My Profile" %}</a> <br>
    <a href="{% url 'authentication:logout' %}">{% trans "Logout" %}</a> <br>
{% else %}
    <a href="{% url "authentication:login" %}">{% trans "Login" %}</a> <br>
    <a href="{% url "authentication:register" %}">{% trans "Sign up" %}</a> <br>
{% endif %}


{% include 'footer.html' %}

</html>

apps/home/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans "My profile" %}
{% endblock %}

{% block body %}

{% include "messages.html" with messages=messages %}

<div class="my-3 py-3 text-center ">
    <h2 class="display-5">{% trans "Welcome to our school!" %}</h2>
  </div>
<div class="d-flex justify-content-center align-items-center"
     style="min-height: 78vh; border-radius: 21px 21px 0 0; overflow: hidden; background-color: #1d1f24;">

    <img class="rounded img-fluid" src="{% static 'Stay.jpg' %}"
         alt="There had to be a picture"
         style="max-width: 100%; height: auto;">
</div>



{% endblock %}