apps/authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from apps.authentication import views

app_name = "apps.authentication"


urlpatterns = [
    path("login/", views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),

    path('settings/', views.UserSettingsView.as_view(), name='settings'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),

    path('users/', views.UsersProfilesView.as_view(), name='users-profiles'),
    path('users/<int:pk>/position/', views.PositionAddView.as_view(), name='update-role'),

    path('activate/<uidb64>/<token>', views.ActivateView.as_view(), name='activate'),

    path("reset_password/", views.PasswordResetView.as_view(), name='reset-password'),

    path(r"reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

]

apps/home/urls.py
from django.urls import path

from apps.home import views

app_name = "apps.home"


urlpatterns = [
    path("", views.HomeView.as_view(), name='home-page')
]

apps/management/urls.py
from django.urls import path

from apps.management import views

app_name = "apps.management"


urlpatterns = [
    # list views
    path("", views.CourseListView.as_view(), name='all-courses'),
    path("my/", views.MyCourseListView.as_view(), name='my-courses'),
    # detail views
    path("<int:pk>/", views.CourseDetailView.as_view(), name='course-detail'),
    # create views
    path("add/", views.CourseCreateView.as_view(), name='create_course'),
    path("<int:pk>/tasks/add/", views.TaskCreateView.as_view(), name='create-task'),
    path("<int:pk>/lectures/add/", views.LectureCreateView.as_view(), name='create-lecture'),
    # update views
    path("<int:pk>/students/update", views.UpdateCourseView.as_view(), name='update-course'),
    # template views
    path("<int:pk>/ratings/", views.RatingView.as_view(), name='ratings'),

]

urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.authentication import JWTAuthentication

from config.settings import base


schema_view = get_schema_view(
    openapi.Info(
        title="LMS API",
        default_version='v1',
        description="",
        contact=openapi.Contact(email="contact@lms.com"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny,],
    authentication_classes=[JWTAuthentication]
)


api_urls = [
    path('courses/', include("apps.management.api_urls")),
    path('courses/<int:pk>/tasks/<int:pktask>/', include("apps.assessment.api_urls")),

    path('accounts/', include("apps.authentication.api_urls")),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', namespace='home')),
    path('courses/', include('apps.management.urls', namespace='management')),
    path('accounts/', include('apps.authentication.urls', namespace='authentication')),
    path('tinymce/', include('tinymce.urls')),
    path('courses/<int:pk>/tasks/<int:pktask>/', include('apps.assessment.urls', namespace='assessment')),
    path('', include('social_django.urls', namespace='social')),

    path('api/', include(api_urls)),



] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT) \
    + static(base.STATIC_URL, document_root=base.STATIC_ROOT)


if base.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += debug_toolbar_urls()




# todo https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/Django/Sessions
# todo try to do data migrations (DML) while dividing app for a few new apps
# todo https://www.geeksforgeeks.org/software-engineering-coupling-and-cohesion/ ; two scoops of django
# todo check pbkdf2 storage password standard; c
# todo книжка искусство джанго
# todo check oauth2, jwt
# todo dive deeper into celery, celery beat, celery beat for task with course data, celery results, caching with redis
# todo check AJAX, GraphQL, jQuery
# todo high scalability .com site to research microservices examples
# todo react js/flux for stupid people

# todo check vim book
# todo implement vue js and nginx

#todo change  .env to secret manager in aws usage for cloud server

apps/management/models.py
import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models, transaction
from django.utils.translation import gettext_lazy as _
from tinymce.models import HTMLField

User = get_user_model()


# Create your models here.
class Course(models.Model):
    teacher = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='courses_as_teacher', null=True)
    title = models.CharField(_('Title'), max_length=255)
    description = models.TextField(_('Description'), null=True, blank=True)
    students = models.ManyToManyField(
        User, related_name='courses_as_student', default=[], blank=True
    )
    start_datetime = models.DateTimeField(_('Start datetime'))
    tags = ArrayField(models.CharField(_('Tags'), max_length=255), default=list)

    def __str__(self):
        return f'<Course: {self.title}>'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        transaction.on_commit(self.assign_permissions)

    def assign_permissions(self):
        content_type = ContentType.objects.get_for_model(Course)

        teacher_perm, created = Permission.objects.get_or_create(
            codename=f"can_access_{self.id}_course_as_teacher",
            name=_(f"Can access {self.title} course as teacher"),
            content_type=content_type,
        )

        students_perm, created = Permission.objects.get_or_create(
            codename=f"can_access_{self.id}_course_as_student",
            name=_(f"Can access {self.title} course as student"),
            content_type=content_type,
        )

        if self.teacher and not self.teacher.has_perm(teacher_perm):
            self.teacher.user_permissions.add(teacher_perm)
            print(f"added permission for teacher: {self.teacher.get_all_permissions()}")

        self.refresh_from_db()

        for student in self.students.all():
            if not student.has_perm(students_perm):
                student.user_permissions.add(students_perm)
                print(f"added permission for student {student.email}: {student.get_all_permissions()}")


class Task(models.Model):
    course = models.ForeignKey(
        "Course", on_delete=models.CASCADE, related_name="tasks"
    )
    title = models.CharField(_("Title"), max_length=100)
    description = models.TextField(_("Description"), max_length=1000)
    max_mark = models.PositiveIntegerField(
        _("Max Mark"), default=5,  validators=[MinValueValidator(1), MaxValueValidator(200)]
    )
    deadline = models.DateField(_("Deadline"), default=datetime.date.today() + datetime.timedelta(days=7), null=True, blank=True)

    def __str__(self):
        return self.title


class Lecture(models.Model):
    course = models.ForeignKey("Course", on_delete=models.CASCADE, related_name="lectures")
    title = models.CharField(_("Title"), max_length=100)
    description = models.TextField(_("Description"), null=True, blank=True)

    def __str__(self):
        return self.title

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{%  static "brightened_logo.png" %}">

    <title>{% block title %}{% endblock %}</title>

    {% block bootstrap_configs %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.0/mdb.min.css" />
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">


    {% endblock %}
    <style>
        body {
        color: #3f4137 !important;
        }
    </style>
    {%  block style %} {% endblock %}
    {% block extras %} {% endblock %}

</head>

{% block header %}
    {% include 'header.html' %}
{% endblock %}


<body>
{% block background %}
<div class="me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden" style="background-color: #5f59f7">
{% block body %}

{% endblock body %}
</div>
{% endblock background %}
</body>

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

{% block extra_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.0/mdb.min.js"></script>
    <script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script>
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>

 {% endblock %}
{% block extra_footer %} {% endblock %}
</html>

templates/dialogs.html
<fieldset id="input-default-form">
    <form method="post">
    {% csrf_token %}
        {% for field in fields %}
            <label for="{{ field.name }}">
                {{ field.title }}
                {% if field.is_required %}
                    <span class="required">*</span>
                {% endif %}
            </label>

            {% if field.name == "description" %}
                    <textarea id="desc" name="{{ field.name }}" rows="4" cols="30"
                              {% if field.is_required %}required{% endif %}>
                    </textarea>
            {% elif field.type == "list" %}
                <select class="form-select" name="{{ field.name }}"
                    {% if field.multiple %} multiple {% endif %}
                    {% if field.is_required %} required {% endif %}>
                    {% if not field.default %}
                        <option disabled selected>Select {{ field.name }}</option>
                    {% else %}
                         <option selected>{{ field.default }}</option>
                    {% endif %}

                    {% for field_option in field.options %}
                        <option value="{{ field_option }}" id="options">{{ field_option }}</option>
                    {% endfor %}

                </select>
            {% else %}
                <input class="form-field"
                   id="{{ field.name }}"
                   type="{{ field.type }}"
                   name="{{ field.name }}"
                   {% if field.default_value %} value="{{ field.default_value }}" {% endif %}
                   {% if field.max %} max="{{ field.max }}" {% endif %}
                   {% if field.min %} min="{{ field.min }}" {% endif %}
                   {% if field.is_required %}required{% endif %}
                   {% if field.placeholder %}placeholder="{{ field.placeholder }}"{% endif %} />  <br>

                {% endif %}
        {% endfor %}
        {%  include 'submit.html' with url='' method='get' text=submit_name id='submit-btn' %}
    </form>
</fieldset>

templates/footer.html
{% load static %}
<footer>
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <img src="{% static "brightened_logo.png" %}" alt="Custom Logo" width="30" height="24">
      </a>
      <span class="text-muted">© 2025 Company, Inc</span>
    </div>
  </footer>

</footer>

templates/form.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

<h1></h1>
<form action="{{ action_url }}" method="post">
    {% csrf_token %}
{{ form.as_p }}

    <button type="submit" class="btn btn-primary">{%  trans btn_name %}</button>
</form>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
        <ul>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <li>{{ error }}</li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
{% endif %}

templates/header.html
{% if request.user.is_authenticated %}
    {% block logged_in_header %}
        {% include 'logged_in_header.html' %}
    {% endblock %}
{% else %}
    {% block logged_out_header %}
        {% include 'logged_out_header.html' %}
    {% endblock %}
{% endif %}

templates/input_form.html
{% extends 'base1.html' %}


{% block title %} {{ title }} {% endblock %}

{% block content %}
    {% include 'dialogs.html' with fields=fields %}
{% endblock content %}



{%  include 'footer.html' %}

templates/logged_in_header.html
{% load i18n %}
{% load static %}
<style>
    .dropdown-item:focus, .dropdown-item:hover {
        color: black !important;
        background-color: white !important;
    }
</style>

<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

        <a href="{% url 'home:home-page' %}" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
            <img src="{%  static "brightened_logo.png" %}" alt="Custom Logo" width="40" height="32">
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'home:home-page' %}" class="nav-link px-2 link-secondary">{% trans "Home" %}</a></li>
          <li><a href="{% url 'management:all-courses' %}" class="nav-link px-2 text-white">{%  trans 'All courses' %}</a></li>

          {% if request.user.position == "student" or request.user.position == "teacher" %}
          <li><a href="{% url 'management:my-courses' %}" class="nav-link px-2 text-white">{%  trans 'My courses' %}</a></li>
          {% endif %}

          {% if perms.management.add_course %}
            <li><a href="{% url "management:create_course" %}" class="nav-link px-2 text-white">{% trans "Add course" %}</a></li>

          {% endif %}

          {% if perms.view_user %}
              <li><a href="{% url "authentication:users-profiles" %}" class="nav-link px-2 text-white">{% trans "Manage Users" %}</a></li>
          {% endif %}
        </ul>


        <div class="dropdown text-end theme-light">
          <a href="{% url "apps.authentication:profile" %}"
             class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                {% if request.user.photo %}
                <img src="{{ request.user.photo.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                {% else %}
                <img src="{% static "default-avatar.jpg" %}" alt="not found photo"  width="32" height="32" class="rounded-circle" >
                {% endif %}
          </a>

          <ul class="dropdown-menu text-small bg-black text-white ">

            <li><a class="dropdown-item  text-white" href="{% url "authentication:settings" %}">Settings</a></li>
            <li><a class="dropdown-item  text-white" href="{% url "authentication:profile" %}">Profile</a></li>
            <li><hr class="dropdown-divider theme-light"></li>
            <li>
                 <form method="post" action="{% url 'apps.authentication:logout' %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="dropdown-item" style="border:none; background:none; padding:15px; cursor:pointer;">
                        {% trans "Sign out" %}
                    </button>
                </form>
          </ul>
        </div>
      </div>
    </div>
  </header>

templates/logged_out_header.html
{% load static %}
{% load i18n %}

<style>
    .btn-outline-light:hover {
        background-color: #171717;
        border-color: #666;
    }

</style>

<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'home:home-page' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <img src="{%  static "brightened_logo.png" %}" alt="Custom Logo" width="40" height="32">
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'home:home-page' %}" class="nav-link px-2 text-secondary">{%  trans 'Home' %}</a></li>
          <li><a href="{% url 'management:all-courses' %}" class="nav-link px-2 text-white">{%  trans 'Our courses' %}</a></li>
        </ul>

        <div class="text-end">
        {% if request.resolver_match.url_name != 'login' %}
          <button type="button" class="btn btn-outline-light me-2">
            <a href="{% url "authentication:login" %}" class="nav-link px-2 text-white" role="button">{% trans "Login" %}</a>
          </button>
        {% endif %}
            {% if request.resolver_match.url_name != 'register' %}
          <button type="button" class="btn btn-warning">
              <a href="{% url "authentication:register" %}" class="nav-link px-2 text-white" role="button">
                {% trans "Sign-up" %}</a>
          </button>
            {% endif %}
        </div>
      </div>
    </div>
  </header>

templates/messages.html
{% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="alert
                {% if message.tags == "success" %}alert-success
                {% elif message.tags == "error" %}alert-danger
                {% elif message.tags == "warning" %}alert-warning
                {% elif message.tags == "info" %}alert-info
                {% else %}alert-primary{% endif %}
                alert-dismissible fade show" role="alert">

                {{ message|safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/submit.html
{% if url %}
 <form action="{{ url }}" method="{{ method }}">
 {% else %}
 <form>
 {% endif %}
    <button type="submit" class="btn btn-primary" id="{{ id }}">{{ text }}</button>
</form>